logging.level:
  root: WARN
  ru.yandex.practicum.filmorate: INFO
  org.zalando.logbook: TRACE

spring:
  sql.init.mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: pass